language: python
python:
  - "3.6"      # current default Python on Travis CI
  - "3.7"
  - "3.7-dev"  # 3.7 development branch
# command to install framework and dependencies
install:
  - python setup.py install
# command to run tests
script:
  - bash -c "hbfupdate" | cat
  - bash -c "hbfconsole -s tests/travis.txt | cat"
